@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{{ __('admin.categories.verification_settings') }} - {{ $category->name }}</h4>
                </div>
                <div class="card-content collapse show">
                    <div class="card-body">
                        <form action="{{ route('admin.categories.update_verification', $category->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-body">
                                <style>
                                    /* The id is generated by the backend, so it has to read as a value
                                       being shown rather than a box waiting for input.
                                       The theme already paints [readonly] #ECEFF1, which is so close to
                                       white that the field looks editable — hence the darker fill, the
                                       dashed border and !important: `.form-control[readonly]` in
                                       bootstrap-extended outranks a single class. */
                                    input.form-control.field-id,
                                    input.form-control.field-id:focus,
                                    input.form-control.field-id:hover {
                                        background-color: #dfe3e8 !important;
                                        color: #6b7280 !important;
                                        border: 1px dashed #aeb6c1 !important;
                                        box-shadow: none !important;
                                        cursor: default;
                                    }
                                </style>
                                @if($errors->any())
                                    <div class="alert alert-danger">
                                        @foreach($errors->all() as $error)
                                            <div>{{ $error }}</div>
                                        @endforeach
                                    </div>
                                @endif

                                <div class="alert alert-warning">
                                    <strong>{{ __('admin.categories.verification_gate_hint_title') }}</strong>
                                    <div class="mt-1">{{ __('admin.categories.verification_gate_hint') }}</div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <fieldset>
                                                <div class="custom-control custom-checkbox">
                                                    <input type="checkbox" class="custom-control-input"
                                                        name="requires_verification" id="requires_verification" value="1"
                                                        {{ $category->requires_verification ? 'checked' : '' }}
                                                        onchange="syncVerificationRequirements()">
                                                    <label class="custom-control-label"
                                                        for="requires_verification">{{ __('admin.categories.requires_verification') }}</label>
                                                </div>
                                            </fieldset>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <fieldset>
                                                <div class="custom-control custom-checkbox">
                                                    <input type="checkbox" class="custom-control-input"
                                                        name="mandatory_service_verification" id="mandatory_service_verification" value="1"
                                                        onchange="syncVerificationRequirements()"
                                                        {{ $category->mandatory_service_verification ? 'checked' : '' }}>
                                                    <label class="custom-control-label"
                                                        for="mandatory_service_verification">{{ __('admin.categories.mandatory_service_verification') }}</label>
                                                </div>
                                            </fieldset>
                                        </div>
                                    </div>
                                </div>

                                <div id="verification_requirements_container" style="{{ $category->requires_verification || $category->mandatory_service_verification ? '' : 'display: none;' }}">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="verification_requirements_en">{{ __('admin.categories.verification_requirements') }} (EN)</label>
                                                <textarea id="verification_requirements_en" class="form-control round" name="verification_requirements[en]"
                                                    rows="3">{{ $category->verification_requirements_en }}</textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="verification_requirements_ar">{{ __('admin.categories.verification_requirements') }} (AR)</label>
                                                <textarea id="verification_requirements_ar" class="form-control round" name="verification_requirements[ar]"
                                                    rows="3">{{ $category->verification_requirements_ar }}</textarea>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row mt-2">
                                        <div class="col-md-12">
                                            <h5>{{ __('admin.categories.verification_fields') }}</h5>
                                            <p class="text-muted mb-1">{{ __('admin.categories.field_id_hint') }}</p>
                                            <div id="dynamic_fields_container">
                                                @if($category->verification_fields)
                                                    @foreach($category->verification_fields as $index => $field)
                                                        <div class="row field-row mb-1">
                                                            <div class="col-md-3">
                                                                <input type="text" name="verification_fields[{{$index}}][id]" class="form-control field-id" placeholder="{{ __('admin.categories.field_id_auto') }}" value="{{ $field['id'] ?? '' }}" readonly>
                                                            </div>
                                                            <div class="col-md-2">
                                                                <select name="verification_fields[{{$index}}][type]" class="form-control">
                                                                    <option value="file" {{ ($field['type'] ?? '') == 'file' ? 'selected' : '' }}>File</option>
                                                                    <option value="text" {{ ($field['type'] ?? '') == 'text' ? 'selected' : '' }}>Text</option>
                                                                    <option value="number" {{ ($field['type'] ?? '') == 'number' ? 'selected' : '' }}>Number</option>
                                                                </select>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <input type="text" name="verification_fields[{{$index}}][label_en]" class="form-control" placeholder="{{ __('admin.categories.field_label') }} (EN)" value="{{ $field['label_en'] ?? '' }}" oninput="previewFieldId(this)">
                                                            </div>
                                                            <div class="col-md-3">
                                                                <input type="text" name="verification_fields[{{$index}}][label_ar]" class="form-control" placeholder="{{ __('admin.categories.field_label') }} (AR)" value="{{ $field['label_ar'] ?? '' }}">
                                                            </div>
                                                            <div class="col-md-1">
                                                                <button type="button" class="btn btn-danger btn-sm" onclick="removeField(this)"><i class="la la-trash"></i></button>
                                                            </div>
                                                        </div>
                                                    @endforeach
                                                @endif
                                            </div>
                                            <button type="button" class="btn btn-info btn-sm mt-1" onclick="addField()"><i class="la la-plus"></i> {{ __('admin.categories.add_field') }}</button>
                                        </div>
                                    </div>
                                </div>

                                <script>
                                    let fieldIndex = {{ $category->verification_fields ? count($category->verification_fields) : 0 }};
                                    function addField() {
                                        const container = document.getElementById('dynamic_fields_container');
                                        const row = document.createElement('div');
                                        row.className = 'row field-row mb-1';
                                        row.innerHTML = `
                                            <div class="col-md-3">
                                                <input type="text" name="verification_fields[${fieldIndex}][id]" class="form-control field-id" placeholder="{{ __('admin.categories.field_id_auto') }}" readonly>
                                            </div>
                                            <div class="col-md-2">
                                                <select name="verification_fields[${fieldIndex}][type]" class="form-control">
                                                    <option value="file">File</option>
                                                    <option value="text">Text</option>
                                                    <option value="number">Number</option>
                                                </select>
                                            </div>
                                            <div class="col-md-3">
                                                <input type="text" name="verification_fields[${fieldIndex}][label_en]" class="form-control" placeholder="{{ __('admin.categories.field_label') }} (EN)" oninput="previewFieldId(this)">
                                            </div>
                                            <div class="col-md-3">
                                                <input type="text" name="verification_fields[${fieldIndex}][label_ar]" class="form-control" placeholder="{{ __('admin.categories.field_label') }} (AR)">
                                            </div>
                                            <div class="col-md-1">
                                                <button type="button" class="btn btn-danger btn-sm" onclick="removeField(this)"><i class="la la-trash"></i></button>
                                            </div>
                                        `;
                                        container.appendChild(row);
                                        fieldIndex++;
                                    }
                                    function removeField(btn) {
                                        btn.closest('.field-row').remove();
                                    }

                                    // Mirrors CategoryController::deriveFieldId so the admin sees the
                                    // id before saving. The server still decides it — this is a preview,
                                    // never the source of truth.
                                    // Mirrors CategoryController::slugFromLabel. Anything past Latin
                                    // Extended-B is refused rather than transliterated into noise, a
                                    // purely numeric id is prefixed, and the result is capped.
                                    function slugFromLabel(label) {
                                        if (label === '' || /[^\u0000-\u024F]/.test(label)) return '';

                                        var slug = label
                                            .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
                                            .toLowerCase()
                                            .replace(/[^a-z0-9]+/g, '_')
                                            .replace(/^_+|_+$/g, '');

                                        if (slug === '') return '';
                                        if (/^[0-9]+$/.test(slug)) slug = 'field_' + slug;

                                        return slug.slice(0, 60).replace(/_+$/, '');
                                    }

                                    function previewFieldId(input) {
                                        var row = input.closest('.field-row');
                                        var idInput = row.querySelector('.field-id');
                                        if (!idInput || idInput.dataset.locked === '1') return;

                                        idInput.value = slugFromLabel(input.value.trim());
                                    }

                                    // An id that came back from the server is settled; typing a new
                                    // English label must not silently repoint uploaded documents.
                                    document.addEventListener('DOMContentLoaded', function () {
                                        document.querySelectorAll('.field-id').forEach(function (el) {
                                            if (el.value.trim() !== '') el.dataset.locked = '1';
                                        });
                                    });
                                    function syncVerificationRequirements() {
                                        // Either gate needs the same requirements filled in, so the
                                        // block follows both checkboxes rather than the first one.
                                        var appWide = document.getElementById('requires_verification');
                                        var serviceOnly = document.getElementById('mandatory_service_verification');
                                        var anyOn = (appWide && appWide.checked) || (serviceOnly && serviceOnly.checked);
                                        document.getElementById('verification_requirements_container').style.display =
                                            anyOn ? 'block' : 'none';
                                    }
                                </script>
                            </div>

                            <div class="form-actions text-right mt-2">
                                <a href="{{ route('admin.categories.index', ['parent_category_id' => $category->parent_category_id]) }}" class="btn btn-warning mr-1 rounded-pill">
                                    <i class="la la-close"></i> {{ __('admin.buttons.cancel') }}
                                </a>
                                <button type="submit" class="btn btn-primary rounded-pill">
                                    <i class="la la-check-square-o"></i> {{ __('admin.buttons.update') }}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
